### ISSUE TITLE
useRenderButton() needs to accept width as number

### ISSUE THREAD

**Issue by ryann3588** [i7N3/google-oauth-library#4]
Seems like there was a change maybe 7/27 or 7/28 in the client code that now only accepts a number value for the width property to render a button vs a string. It doesn't render the button if you pass in a string value for width.

**Comment by i7N3** [comment]
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66207
- https://github.com/MomenSherif/react-oauth/issues/281

**Comment by ryann3588** [comment]
Thanks for the quick response. I was getting a work around in place when I noticed you updated the package. Awesome!
