### ISSUE TITLE
Angular Support

### ISSUE THREAD

**Issue by iMogs370** [i7N3/google-oauth-library#5]
Hi, 
I am using angular 16 and am having issues getting the button to render.  It's just displaying the div that's created "<div></div>" and nothing inside it.

Here is the ts:
import { AfterViewInit, Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { GoogleOAuthProvider } from 'google-oauth-gsi';
import env from '../../env/env';

@Component({
  selector: 'app-google-login',
  templateUrl: './google-login.component.html',
  styleUrls: ['./google-login.component.scss']
})
export class GoogleLoginComponent implements AfterViewInit  {

  @ViewChild('signInButton') signInButtonRef: ElementRef;

  constructor(private elementRef: ElementRef) {}

  ngAfterViewInit(): void {
    const provider = new GoogleOAuthProvider({
      clientId: env.googleAuth,
      onScriptLoadError: () => console.log('onScriptLoadError'),
      onScriptLoadSuccess: () => console.log('onScriptLoadSuccess'),
    });

    const login = provider.useGoogleLogin({
      flow: 'auth-code',
      onSuccess: (res) => console.log('Logged in with Google', res),
      onError: (err) => console.error('Failed to login with Google', err),
    });

    const buttonEl = document.createElement('div');

    const renderButton = provider.useRenderButton({
      element: buttonEl,
      useOneTap: false,
      width: 100,
      type: 'standard',
      theme: 'outline',
      size: 'large',
      text: 'signin_with',
      shape: 'rectangular',
      logo_alignment: 'left',
      onError: () => console.error('Failed to render button'),
      onSuccess: (res) => console.log('Logged in with Google (render button)', res),
    });

    buttonEl.addEventListener('click', () => {
      if (login) login();
    });

    renderButton();

    console.log('Button content:', buttonEl);

    this.elementRef.nativeElement.querySelector('#signInButton').appendChild(buttonEl);
  }
}

html: 
<div #signInButton id="signInButton"></div>

Inspection:
<div _ngcontent-ng-c1220835659="" id="signInButton"><div></div></div>

**Comment by i7N3** [comment]
@iMogs370 
Here is working example:
https://github.com/i7N3/google-oauth-gsi/tree/main/examples/angular
